<?php
/**
 * Страница "Панель файлов".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Files panel</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/filepanel.png' ?>" />
    </div>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Name.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Full name.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Size.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Type.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam 
        voluptua;</li>
        <li><b>MIME-type.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Permissions.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Last accessed.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;</li>
        <li><b>Last modified.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-home.svg' ?>" width="32px" height="32px"/> <b>Root folder.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-up.svg' ?>" width="32px" height="32px"/> <b>Go up.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-delete.svg' ?>" width="32px" height="32px"/> <b>Delete.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>" width="32px" height="32px"/> <b>Refresh.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-find.svg' ?>" width="32px" height="32px"/> <b>Search.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-profile_on.svg' ?>" width="32px" height="32px"/> <b>Profiling.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-select.svg' ?>" width="32px" height="32px"/> <b>Select.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-upload.svg' ?>" width="32px" height="32px"/> <b>Upload.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-download.svg' ?>" width="32px" height="32px"/> <b>Download.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-compress.svg' ?>" width="32px" height="32px"/> <b>Compress.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-extract.svg' ?>" width="32px" height="32px"/> <b>Extract.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-rename.svg' ?>" width="32px" height="32px"/> <b>Rename.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-view.svg' ?>" width="32px" height="32px"/> <b>Просмотреть.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-permissions.svg' ?>" width="32px" height="32px"/> <b>Permissions.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-attributes.svg' ?>" width="32px" height="32px"/> <b>Information.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-grid.svg' ?>" width="32px" height="32px"/> 
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-list.svg' ?>" width="32px" height="32px"/> <b>Grid / List.</b> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.
        </li>
    </ul>
</article>