<?php
/**
 * Страница "Панель дерева папок".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Панель дерева папок</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/folderpanel.png' ?>" />
    </div>
    <p>Панель дерева папок состоит из списка папок в виде дерева и панели инструментов для совершения операций над этими папкам.</p>
    <h2>Панель инструментов</h2>
    <ul class="g-help-list">
    <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-collapse.svg' ?>" width="16px" height="16px"/> <b>Свернуть.</b> Сворачивает все узлы дерева папок;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-expand.svg' ?>" width="16px" height="16px"/> <b>Развернуть.</b> Разворачивает все узлы дерева папок;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>" width="16px" height="16px"/> <b>Обновить.</b> Обновляет все узлы дерева папок;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-settings.svg' ?>" width="16px" height="16px"/> <b>Настройки.</b> Переходит к настройке <a href="<?= $url('index', 'extension:gm.be.references.media_folders') ?>">структуры медиапапок</a>;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-edit.svg' ?>" width="16px" height="16px"/> <b>Редактировать медиапапку.</b> Показывает <a href="<?= $url('form', 'extension:gm.be.references.media_folders') ?>">окно</a> для редактирования выбранной медиапапки;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-attributes.svg' ?>" width="16px" height="16px"/> <b>Редактировать профиль.</b> Показывает <a href="<?= $url('form', 'extension:gm.be.references.folder_profiles') ?>">окно</a> для редактирования профиля выбранной медиапапки.
        </li>
    </ul>
</article>