<?php
/**
 * Страница "Панель дерева папок".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Folder tree panel</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/folderpanel.png' ?>" />
    </div>
    <p>The folder tree panel consists of a tree-like list of folders and a toolbar for performing operations on these folders.</p>
    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-collapse.svg' ?>" width="16px" height="16px"/> <b>Collapse.</b> Collapses all nodes of the folder tree;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-expand.svg' ?>" width="16px" height="16px"/> <b>Expand.</b> Expands all nodes of the folder tree;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-refresh.svg' ?>" width="16px" height="16px"/> <b>Refresh.</b> Refreshes all nodes of the folder tree;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-settings.svg' ?>" width="16px" height="16px"/> <b>Settings.</b> Proceeds to setting up the <a href="<?= $url('index', 'extension:gm.be.references.media_folders') ?>">media folder structure</a>;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-edit.svg' ?>" width="16px" height="16px"/> <b>Edit media folder.</b> Shows <a href="<?= $url('form', 'extension:gm.be.references.media_folders') ?>">a window</a> for editing the selected media folder;
        </li>
        <li>
            <img class="g-help-icon g-icon-svg g-icon-m_color_neutral-dark" src="<?= $assetsUrl, '/images/toolbar/icon-attributes.svg' ?>" width="16px" height="16px"/> <b>Edit folder profile.</b> Shows <a href="<?= $url('form', 'extension:gm.be.references.folder_profiles') ?>">a window</a> for editing the profile of the selected media folder.
        </li>
    </ul>
</article>