<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью расширения модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Media files</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Images, videos and files that you upload and use on site pages.</p>

    <h2>Contents:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('filepanel') ?>">Files panel</a></li>
        <li><a href="<?= $url('folderpanel') ?>">Folder tree panel</a></li>
        <li><a href="<?= $url('settings') ?>">Settings</a></li>
    </ul>
</article>